### ISSUE TITLE
DeathStalker Chroma regions not being set?

### ISSUE THREAD

**Issue by antonpup** [CoraleStudios/Colore#219]
I am having difficulties with setting color regions for the DeathStalker Chroma. Lighting works for other keyboards like the BlackWidow.

Here's a link to the issue a user with a DeathStalker created.  https://github.com/antonpup/Aurora/issues/286

**Comment by njbmartin** [comment]
Checked out the issue posted on your project. It might require the use of the grid reference instead of targeting the keys. Chroma SDK has two `Custom` effects for keys. `CHROMA_CUSTOM` uses a grid reference (eg. `1,1`) where as CHROMA_CUSTOM_KEY uses the `RZKEY` keymaps.

I don't have a deathstalker chroma, but I'll try and get hold of one. In the meantime, you may need to work with the user to fully test this.

**Comment by njbmartin** [comment]
Saying that, I noticed the user said they couldn't see any colours when setting the whole keyboard, which is definitely strange. Unless, it could be that `CHROMA_CUSTOM_KEY` is not supported on the deathstalker...

I've noticed we use `CHROMA_CUSTOM_KEY` for grid too, which may in this case be incompatible with the deathstalker.

**Comment by antonpup** [comment]
Any advancements on this?

**Comment by roxaskeyheart** [comment]
I can confirm that DeathStalker will not respond to .SetAll() commands

**Comment by njbmartin** [comment]
I think I know why, will have a look.

**Comment by njbmartin** [comment]
I now have a Deathstalker Chroma so I can investigate this further.

**Comment by njbmartin** [comment]
So I've done some initial investigation now I've been sent a Deathstalker, and it turns out Colore is setting position incorrectly so there's some fixes on the way!

However, I have highlighted to Razer that we cannot use CHROMA_CUSTOM_KEY with the Deathstalker, which is inconsistent with the rest of the devices.

**Comment by Sharparam** [comment]
Fix being tracked in #243.

This will make it a bit cumbersome to make effects that work on *all* keyboards, as the Deathstalker will need special treatment. One way to do it in the proposed solution is to send off a copy of the `CUSTOM_KEY` non-Key array to a `CUSTOM` effect. But without querying for the connected device there is no smooth way to use key effects on devices that support it, and fall back internally on the grid effect if keys are not supported.

**Comment by Sharparam** [comment]
Implemented now. Use the `IsDeathstalkerConnected` property on `IKeyboard` to check for Deathstalker presence and then utilize the `SetDeathstalkerZoneAsync` and `SetDeathstalkerAsync` methods to set zone colors. `SetAllAsync` now works on the Deathstalker as well.
