### ISSUE TITLE
Game Dog v5.0 doesn't starting

### ISSUE THREAD

**Issue by blessedbyb** [CoraleStudios/Colore#297]
## Description

I bought a Razer Blackwidow V3 keyboard, there is no support for dota 2 and cs go games in Razer Synapse. So I downloaded Game dog of all versions. On the first version (2.4) the system ignored it, but the program worked well with no errors. On the second version (3.7), it gave out a lot of errors and didn't work at all. On the latest version (5.0), the program starts and keyboard reacts, but then it crashes on logo and keyboard go off. Also in Synapse I turned on all that was in the instructions and in dota 2 launch properties I set -gamestateintegration.
## Expected Behavior

The application should integrate Dota 2 with backlit keyboard

## Actual Behavior

The application does not start
## Possible Fix

I have no idea
## Steps to Reproduce

1.Download the application
2.Start it
3.Wait for the launch
4.See that the application is crashed on the logo

## Context

It does not allow to integrate Dota 2 on the backlight on my keyboard, I wanted to run it
## Your Environment

* Version of Colore used:
* SDK mode (Native or REST API):
* Synapse version installed:3.0
* Chroma SDK version in use: last version
* Operating System and version (e.g. Windows 10 x64):Windows 11 x64
* Link to your project (if available):

**Comment by Sharparam** [comment]
This is likely an issue with GameDog rather than Colore: https://gitlab.com/Chromatin/GameDog

Their issue tracker is here: https://gitlab.com/Chromatin/GameDog/-/issues

Also tagging @WolfSpiritM since I think they are involved with that project.

Closing this for now since I don't think it's a Colore issue. If you hear back from them and it's a Colore issue after all, please re-open this issue (I think you should be able to re-open, if not just let us know).
