### ISSUE TITLE
Color.Orange is, well, not orange

### ISSUE THREAD

**Issue by njbmartin** [CoraleStudios/Colore#67]
It's a wonderful shade of blue.

**Comment by Sharparam** [comment]
Almost as if it should be kept as an easter egg.

@brandonscott I thought we fixed this, damnit.

**Comment by njbmartin** [comment]
Also the colour definitions are a mix of hex and RGB, may as well make them all RGB.

**Comment by njbmartin** [comment]
@Sharparam Half life 3 confirmed?

**Comment by Sharparam** [comment]
Changing the value of the color breaks backwards compatibility with code that depends on the Orange color being Blue.

As silly as that sounds, it schedules this change for 3.0.

**Comment by njbmartin** [comment]
@Sharparam Fairly certain that Orange is almost certainly not supposed to be Blue.

I'm using new Color(255,140,0) as an alternative for now, as would others.

**Comment by Sharparam** [comment]
Backwards compatibility breakage is backwards compatibility breakage. Code that depends on Orange having the value it does will break if this is shipped as a minor version.

**Comment by njbmartin** [comment]
But why would anyone be using Colore.Orange when it's not orange?

**Comment by Sharparam** [comment]
The color orange having its value changed means that the change will not be compatibly with code targeting Colore 2.x. This bumps the major version up: http://semver.org/

**Comment by brandonscott** [comment]
As much as I agree with you @njbmartin and your argument is sound, if we are to follow best practice, then this does indeed break backwards compatibility.

It is however noteworthy that often these things are not as black and white as @Sharparam describes them.  A developer is unlikely to use Color.Orange when it is so obviously blue.  

I see little point in engineering a deprecated version of this (not implying that this was an action we would take) and recommend we simply update the value as part of 3.0.

**Comment by njbmartin** [comment]
Agreed. We should perhaps maintain a list of known issues within the readme.

**Comment by brandonscott** [comment]
Or the wiki?

**Comment by OrangeDog** [comment]
Is every bug fix going to be semver-major then, as they all break backwards-compatibility with code relying on the broken behaviour? What about new features, and code relying on the lack of the feature?

**Comment by Sharparam** [comment]
Introducing a new feature does not (usually) break backwards compatibility
because components that old code relies on still exists and exhibits the
same behaviour.

As soon as a change is introduced that will cause existing code to behave
differently is when backwards compatibility has been broken and the major
version is increased.

**Comment by mathieumg** [comment]
By that logic every bug fix would be breaking, no? Semver states:

> PATCH version when you make backwards-compatible bug fixes

This sound like a bug fix since orange should be, well, orange, updating to this version won't cause breakage/crashes, and anybody who used orange to mean blue instead of blue to mean blue had no reason to do so.

**Comment by Sharparam** [comment]
Backwards-compatible and backwards-incompatible are not subjective opinion-based concepts. A change that is not compatible with previous code is a change that is not compatible with previous code.

`255 != 0` and there is no way around such a mathematical concept.

Whether or not code "should" behave in one way or another is not our place to say. The dev could be colorblind and relying on the definition of `Color.Orange` to be, in fact, orange. Changing this expectation, whether justified or no, changes the current effect of existing code.

The only two hotfixes that have been made so far on Colore (#75 and #60) both fixed code to behave as expected by outside code (#75) or restored broken code that had introduced compatibility-breaking bugs (#60). Thus only the *PATCH* component of the version number had to be increased, as expectations made by outside code remained correct.

With `Color.Orange` there are two possible expectations made by outside code: That the color is orange, or that it is blue (from code that have found out the first assumption was incorrect). Changing it to an actual orange color is now going to break the assumption by the second group and only apply to assumptions made by future code, which is exactly the kind of scenario that would warrant an increase of the *MAJOR* component of the version number.

It is possible that this specific issue is somewhat of an edge case, but since the fact of the matter is that the fix would change data that is exposed to third-party code, we're going to err on the side of caution and delay the fix until v3.0.

**Comment by Sharparam** [comment]
Fixed in #96
